# Generated by Django 6.0.7 on 2026-08-02 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('COURSE_CREATED', 'Course created'), ('COURSE_UPDATED', 'Course updated'), ('COURSE_REMOVED', 'Course removed'), ('ENROLLMENT', 'Enrollment'), ('PURCHASE', 'Purchase'), ('ADMIN_ACTION', 'Admin action'), ('SYSTEM_ERROR', 'System error')], max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
