# Generated by Django 6.0.7 on 2026-08-02 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('registration', 'Registration'), ('courses', 'Courses'), ('payments', 'Payments'), ('password', 'Password'), ('dashboard', 'Dashboard'), ('general', 'General')], default='general', max_length=20)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated extra terms to aid retrieval matching.', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'FAQ entries',
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to=settings.AUTH_USER_MODEL)),
                ('matched_faqs', models.ManyToManyField(blank=True, related_name='chat_logs', to='chatbot.faqentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
